version: "2"
services:
  node:
    image: "node:8"
    user: "node"
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/usr/src/app
    expose:
     - "8080"
    command: "npm run production"
    ports:
      - 0.0.0.0:8080:8080/tcp
